### ISSUE TITLE
Build is broken

### ISSUE THREAD

**Issue by williamrijksen** [appcelerator-modules/ci#10]
Build gives the following output:

```

/Users/travis/Library/Application Support/Titanium/mobilesdk/osx/6.1.0.v20170122203602/node_modules/fields/lib/prompter.js:333

	process.stdin.setRawMode(true);

               ^

TypeError: process.stdin.setRawMode is not a function

    at File._get (/Users/travis/Library/Application Support/Titanium/mobilesdk/osx/6.1.0.v20170122203602/node_modules/fields/lib/prompter.js:333:16)

    at File.prompt (/Users/travis/Library/Application Support/Titanium/mobilesdk/osx/6.1.0.v20170122203602/node_modules/fields/lib/types/file.js:87:7)

    at /Users/travis/.nvm/versions/node/v4.7.2/lib/node_modules/titanium/lib/cli.js:846:12

    at /Users/travis/.nvm/versions/node/v4.7.2/lib/node_modules/titanium/lib/cli.js:585:12

    at conf.options.android-sdk.prompt (/Users/travis/Library/Application Support/Titanium/mobilesdk/osx/6.1.0.v20170122203602/android/cli/commands/_build.js:323:8)

    at Object.opt.prompt (/Users/travis/.nvm/versions/node/v4.7.2/lib/node_modules/titanium/lib/cli.js:584:11)

    at CLI.<anonymous> (/Users/travis/.nvm/versions/node/v4.7.2/lib/node_modules/titanium/lib/cli.js:838:9)

    at /Users/travis/.nvm/versions/node/v4.7.2/lib/node_modules/titanium/node_modules/async/dist/async.js:4053:5

    at q.process (/Users/travis/.nvm/versions/node/v4.7.2/lib/node_modules/titanium/node_modules/async/dist/async.js:2479:17)

    at Immediate.<anonymous> (/Users/travis/.nvm/versions/node/v4.7.2/lib/node_modules/titanium/node_modules/async/dist/async.js:2292:16)
```

How to solve?

**Comment by hansemannn** [comment]
Likely caused by https://github.com/sgtcoolguy/ci/pull/1

**Comment by cb1kenobi** [comment]
@williamrijksen You are getting this error because the build is being run from a process that doesn't have a TTY terminal. In other words, you are running the build from some script or as a subprocess. You can fix this by simply passing in `--no-prompt`. You should also pass in `--no-progress`.

**Comment by williamrijksen** [comment]
@cb1kenobi Where should i add these variables?

**Comment by cb1kenobi** [comment]
Where ever you invoke the build.

```
appc run --no-prompt --no-progress --build-only
```

**Comment by williamrijksen** [comment]
Now i ran into the following issue:

```
[ERROR] Invalid "--android-sdk" value "/Users/travis/Library/Application"
```

**Comment by cb1kenobi** [comment]
The path has to be wrapped in quotes to handle spaces in paths.
